vm:
  box-default: chef/debian-7.4
  hostname: ipt.biodiversity.agr.gc.ca
  memory: 4096
  cpus: 2

  provider:
    openstack:
      enabled: true # Set to 'true' if you want to use the openstack provider (vagrant-openstack-plugin required)
      box: dummy
      vm-name: 'IPT'
      box-url: https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box
      username: admin
      api-key: admin
      flavor: m1.small
      project-name: admin
      image: Ubuntu 14.04 Trusty
      identity-auth-url: http://openstack-test.biodiversity.agr.gc.ca:5000/v2.0/tokens
      ssh-username: ubuntu # Typically set in the image (default: ubuntu)
      ssh-key-path: ~/.ssh/iyad # Location of the SSH private key
      keypair-name: iyad # Key pair name in OpenStack (You must import it prior to using vagrant)
      floating-ip: auto # Provide a floating-ip address, or set to 'auto', or leave it empty
    libvirt:
      box: debian-7.4
    aws:
      vm-name: 'IPT'
      box: ubuntu_aws  # A dummy box that Vagrant requires for backwards compatibility
      box-url: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box  # The path for the dummy box
      access-key-id:  ABCDEFGHIJKLMNOP # AWS access id
      secret-access-key: ABCDEFHIJKLMNOPQRSTUVWXYZ1234567890 # AWS secret key
      keypair-name: example-keypair  # Key pair name in AWS
      ssh-key-path: ~/.ssh/example-keypair.pem # Key pair name in OpenStack
      ssh-username: ubuntu # Username to ssh with - set in the image
      instance-type: t2.micro # The instance type defines the CPU, Mem, and Storage for the VM 
      image: ami-8827efe0 # Amazon Machine Image identifier
      elastic-ip: # Provide an existing elastic-ip address, or set to 'auto' to assign a new one, or leave it empty
  networking:
    # NOTE: Networking is ignored for the OpenStack provider.
    type: public # private: forward traffic through host IP.  public: provide VM with its own IP.
    public:
      bridge: bond0 # Device to bridge on the host
      ip: 10.128.124.131 # IP of VM
      gateway: 10.128.124.1 #  Gateway for the above IP
      dns: 10.117.10.52 # DNS server - only 1 entry supported
    private:
      port-forward: #ports to forward guest-port: host-port
        80: 4567
        22: 10022
  shared-folders:
  # - guest-path: location to mount on guest
  #   host-path: location on host - will be created if doesn't exist
  #   owner: (optional) the owner of the folder used in VirtualBox's mounts
  #   group: (optional) the group of the folder used in VirtualBox mounts
    - guest-path: /ipt_data
      host-path: ./ipt_data
